name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ubuntu
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          cd Multi-Environment-CI-CD-Pipeline-with-Cost-Monitoring/

          git pull origin dev

          docker stop cicd-container || true
          docker rm cicd-container || true

          docker build -t cicd-app .

          docker run -d -p 3000:3000 --name cicd-container cicd-app